---

# plugins:
#   # https://github.com/jest-community/eslint-plugin-jest
#   - jest
#   # https://github.com/babel/eslint-plugin-babel
#   - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  es6: true
  node: true
  # jest: true

# https://github.com/babel/babel-eslint

# parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  linebreak-style: 0 
  no-console: 0 
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version

