name: lint

on:
  push:
      branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
       - name: npm install
        run: |
          make install
      - uses: actions/checkout@v1
      - name: Run linter
        run: make lint
